# Generated by Django 5.2.4 on 2025-09-15 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_valid',
            field=models.BooleanField(default=False),
        ),
    ]
